spring.application.name=weather-service
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.endpoints.web.exposure.include=*

# Resilience4J
resilience4j.circuitbreaker.instances.weatherService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.weatherService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.weatherService.failureRateThreshold=50

weather.api.url=https://api.openweathermap.org/data/2.5
weather.api.key=Your_API_KEY